### ISSUE TITLE
mame starts and capture the mouse

### ISSUE THREAD

**Issue by farvardin** [bintracker/bintracker#4] opened 2020-06-20 15:49 UTC
if mame could start without capturing the mouse, it would provide a better bintracker experience. 

At the moment, after opening a song, when mame starts, it captures the mouse (the pointer will disappear) and I have to use "alt" + "tab" to get my mouse again.

I've looked at the man pages, and this option doesn't seems to be possible.

**Comment by utz82** [comment] 2020-06-20 18:33
Not cool, mouse capturing should normally be disabled in MAME by default. I can't reproduce it on 0.209, so something must've changed in the meantime. Does adding `-nomouse` to the options in `emulators.scm` help?

**Comment by farvardin** [comment] 2020-06-20 19:15
when I've read the man page, I thought this option wasn't relevant because it said the "default is OFF (nomouse)" (and I also though it was for disabling mouse in emulated system). But maybe it was changed afterwards. Adding this option prevents capturing the mouse, so you could add this in emulators.scm!

**Comment by utz82** [comment] 2020-06-20 19:51
Good idea, I've added it.
I don't think that this is intentional, actually. Care to file a bug against https://github.com/mamedev/mame ? I'll do it myself if you can't be bothered.

**Comment by farvardin** [comment] 2020-06-20 20:25
done: https://github.com/mamedev/mame/issues/6847

**Comment by utz82** [comment] 2020-06-24 14:15
Closing this, since not much else can be done regarding this from Bintracker's side.

**Closed by utz82** 2020-06-24 14:15 UTC
