### ISSUE TITLE
fast scrolling with arrow crashes bintracker

### ISSUE THREAD

**Issue by farvardin** [bintracker/bintracker#6] opened 2020-06-20 18:32 UTC
when scrolling with arrow it sometimes (rather often) crashes the tracker, leaving this message in the console:

>  too many nested evaluations (infinite loop?)
>     while executing
> "autoName"
>     (procedure "callToScm" line 3)
>     invoked from within
> "callToScm g251 Up"
>     (command bound to event)

**Comment by utz82** [comment] 2020-06-20 18:39
Do you mean scrolling with the arrow keys, or by clicking on the arrows of the scrollbar widget?

**Comment by farvardin** [comment] 2020-06-20 18:48
I meant for moving the cursor with the arrows on my keyboard. Probably the key repetition is a bit too fast for bintracker, but it shouldn't crash like that.

**Comment by utz82** [comment] 2020-06-20 19:20
Hm, that's strange. I thought for a moment that I forgot to apply a lock but that's not the case, so actually the BT window should not be receiving any more keypress events before it has processed the current one.

Could you try the following: In `bt-gui.scm`, line 2556 (after `(begin ...`, insert the line `(tk-eval "tk busy .")`. After the now line 2558, insert the line `(tk-eval "tk busy forget .")`. The whole expression should look like this:

```Scheme
`((<<BlockMotion>> ,(lambda (keysym)
  			     (begin
			       (tk-eval "tk busy .")
  			       (ui-cancel-selection buf)
  			       (ui-blockview-move-cursor buf keysym)
			       (tk-eval "tk busy forget .")))
  			  %K)
 ...)
```

Recompile and let me know if that helps. Note that recompiling will trash your configuration settings. Make a backup of your config dir in `build`, or copy `build/config/` over the `config` dir in the main directory.

If it helps then it might be a good idea to do the same for the following s-expression (the one starting with `<<BlockSelect>>`, until I manage to fix this properly.

**Comment by farvardin** [comment] 2020-06-20 19:43
no, it's actually worse, I've recompiled it with those additions, but now even if I can run bintracker, using arrows would just make freezing the interface (the mouse arrow changes like it's loading something and it just halts like that)

**Comment by utz82** [comment] 2020-06-20 19:57
Meh. Ok, I'll look into it tomorrow if I have time.
Could you tell me your Tcl/Tk version? Eg, in a terminal, launch `tclsh`, then type `info patchlevel`. (Ctrl-d quits out of tclsh.)

**Comment by farvardin** [comment] 2020-06-20 20:06
> % info patchlevel
> 8.6.8

**Comment by utz82** [comment] 2020-06-20 20:25
Thanks. Same here so that's one thing I can rule out.

**Comment by utz82** [comment] 2020-06-23 18:05
Ok, a new attempt. Could you try to change the `if` condition starting at bt-gui.scm:2548 the following

```Scheme
(if (pair? (cdr event-spec))
    `(,(lambda (keysym)
          (tk-eval "tk busy .")
          ((cadr event-spec) keysym)
          (tk-eval "tk busy forget ."))
      ,(caddr event-spec))
    (lambda () (tk-with-lock (cdr event-spec))))
```

Similar idea as before, but without the lock.

**Comment by farvardin** [comment] 2020-06-23 22:38
I got a 

> Error: (line 4175) unterminated list, starting in line 2543

> Error: shell command terminated with non-zero exit status 17920: '/usr/local/bin/chicken' '../bt-gui.scm' -output-file 'bt-gui.c' -dynamic -feature chicken-compile-shared -debug-level 3 -emit-import-library bt-gui

maybe you could commit this into a separate branch, or send me the full file, I'm not sure I did it right. Is scheme picky about the indentation, like python?

**Comment by utz82** [comment] 2020-06-24 11:32
Sure, here's the file. (Some other changes added as well but should work nevertheless).
[bt-gui.scm.txt](https://github.com/bintracker/bintracker/files/4825041/bt-gui.scm.txt)

Scheme doesn't care about indentation. It's very picky about missing parenthesis though. Which editor are you using? Have a look if there's a semantic/structural editing plugin for it (usually called "paredit"). The usual suspects (Vim, VS Code, Atom) all have one. What it does at a basic level is preventing you from accidentally unbalancing parenthesis. Eg. it only ever lets you delete an open parens if you also delete the matching closing parens, and it only lets you delete a closing parens if the list it belongs to is empty, eg. if it immediately follows an open parens. Uhh I don't think I'm explaining it very well, so maybe this animated guide is better: http://danmidwood.com/content/2014/11/21/animated-paredit.html
Keybindings will be different in your editor but the prinicple remains the same.

**Comment by utz82** [comment] 2020-06-29 22:21
Accidentally pushed the proposed fix earlier. That was a bad idea; as it turns out, tk-with-lock is very much required. I've now pushed a new version which locks the GUI first, then applies tk-with-lock. Could you test if this solves the problem for you?

**Comment by utz82** [comment] 2020-06-30 19:12
Nope, certainly won't fix the issue. In fact I'm now getting those "too many nested evaluations" errors as well. Which is good because at least I can reproduce the issue now.

**Comment by farvardin** [comment] 2020-06-30 21:47
Ok, I'll try to compile the new code during this week. I don't have as much time as i want at the moment!

**Comment by utz82** [comment] 2020-06-30 21:53
Don't worry for now. The current fix doesn't work and the problem still exists. I'll need to dig deeper but I also don't have so much time atm. Thanks for all your help so far!

**Comment by utz82** [comment] 2023-02-04 14:48
Should be fixed.

**Closed by utz82** 2023-02-04 14:48 UTC
Labels: bug
